riscv: andes: add CONFIG_PHYS_ADDR_T_64BIT for Andes RV32
Enabling PHYS_ADDR_T_64BIT allows andes-cache.c to perform cache
operations using 64-bit physical addresses on a 32-bit system.

When enabling PHYS_ADDR_T_64BIT on RV32, it is necessary to
set MAX_POSSIBLE_PHYSMEM_BITS. This setting is located
in arch/riscv/include/asm/pgtable-32.h.

However, including arch/riscv/include/asm/xip_fixup.h,
which in turn includes <linux/pgtable.h>,
references the following condition in include/linux/pgtable.h:

if !defined(MAX_POSSIBLE_PHYSMEM_BITS) && !defined(CONFIG_64BIT)
error Missing MAX_POSSIBLE_PHYSMEM_BITS definition

This causes a compilation error:

In file included from ./arch/riscv/include/asm/xip_fixup.h:8,
   from arch/riscv/kernel/head.S:17:
   ./include/linux/pgtable.h:1578:2: error: #error Missing
   MAX_POSSIBLE_PHYSMEM_BITS definition
   1578 | #error Missing MAX_POSSIBLE_PHYSMEM_BITS definition
   make[4]:[scripts/Makefile.build:360: arch/riscv/kernel/head.o] Error 1
   make[3]:[scripts/Makefile.build:480: arch/riscv/kernel] Error 2

Signed-off-by: charles <dminus@andestech.com>